name: Build and deploy Node.js app to Azure Web App - sophix-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        working-directory: sophix-backend
        run: npm install

      - name: Build application
        working-directory: sophix-backend
        run: npm run build

     - name: Upload artifact
  uses: actions/upload-artifact@v4
  with:
    name: backend
    path: sophix-backend
          

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: backend

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5C01D14DEBF340F28B14FE45B09274AE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FD4E4EF9CC8047B79BF8B145B3337E97 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E023300344904B1EAD992421D8C5AAAD }}

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: sophix-backend
          slot-name: Production
          package: .
