name: Build and deploy Node.js app to Azure Web App - sophix-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    defaults:
      run:
        working-directory: sophix-backend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: sophix-backend/package-lock.json

      - run: npm ci

      - run: npm run build

      - run: |
          mkdir deploy
          cp -r dist deploy/
          cp package.json deploy/
          cp package-lock.json deploy/

      - uses: actions/upload-artifact@v4
        with:
          name: sophix-backend
          path: sophix-backend/deploy

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: sophix-backend

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E60E774A429C4B8DB669013F0193C8B0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B77D8812959740DFBD8A439FD64FD4C7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F6FF879C0B2F4D6C94E024310F2ACF32 }}

      - uses: azure/webapps-deploy@v3
        with:
          app-name: sophix-backend
          slot-name: Production
          package: .
